# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticesetting',
            name='medium_new',
            field=models.IntegerField(blank=True, choices=[(0, 'email')], max_length=1, null=True, verbose_name='medium_new'),
        ),
        migrations.AlterField(
            model_name='noticesetting',
            name='medium',
            field=models.CharField(blank=True, choices=[(0, 'email')], max_length=1, null=True, verbose_name='medium'),
        ),
    ]
