# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_notifications', '0005_noticesetting_medium_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticesetting',
            name='medium_new',
        ),
        migrations.AlterField(
            model_name='noticesetting',
            name='medium',
            field=models.IntegerField(choices=[(0, 'email')], verbose_name='medium'),
        ),
    ]
