# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 14:45
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count

def remove_duplicates(apps, schema_editor):
    NoticeSetting = apps.get_model('pinax_notifications', 'NoticeSetting')
    dupes = NoticeSetting.objects.values('notice_type', 'user').annotate(count=Count('id')).filter(count__gt=1)
    for dupe in dupes:
        notice_settings = NoticeSetting.objects.filter(user=dupe['user'], notice_type=dupe['notice_type'])
        keeper = notice_settings.last()
        notice_settings.exclude(id=keeper.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_notifications', '0006_auto_20170228_1420'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates)
    ]
