# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinax_notifications', '0006_auto_20170228_1420'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='noticesetting',
            unique_together=set([('user', 'notice_type', 'medium')]),
        ),
    ]
